spring:
  application:
    name: ecommerce-api-gateway

  cloud:
    gateway:
      routes:
        - id: ecommerce-product-service
          uri: lb://ECOMMERCE-PRODUCT-SERVICE
          predicates:
            - Path=/products/**

        - id: ecommerce-order-service
          uri: lb://ECOMMERCE-ORDER-SERVICE
          predicates:
            - Path=/orders/**

        - id: ecommerce-auth-service
          uri: lb://ECOMMERCE-AUTH-SERVICE
          predicates:
            - Path=/auth/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true